FROM python:3.11-slim

ARG REPO_URL

RUN apt-get update && apt-get install -y --no-install-recommends \
	&& rm -rf /var/lib/apt/lists/*

WORKDIR /opt/StaticJinjaPlus

ADD ${REPO_URL} /tmp/app.tar.gz

RUN tar -xzf /tmp/app.tar.gz --strip-components=1 -C /opt/StaticJinjaPlus && \
	rm -rf /tmp/app.tar.gz

RUN mv /opt/StaticJinjaPlus/templates_example /opt/StaticJinjaPlus/templates

RUN pip3 install --no-cache-dir -r requirements.txt

ENTRYPOINT ["python3", "main.py"]

CMD ["--help"]
