FROM ubuntu:22.04@sha256:0e0a0fc6d18feda9db1590da249ac93e8d5abfea8f4c3c0c849ce512b5ef8982

ARG REPO_URL

RUN apt-get update && apt-get install -y --no-install-recommends \
	python3 \
	python3-pip \
	git \
	&& rm -rf /var/lib/apt/lists/*

WORKDIR /opt/StaticJinjaPlus

ADD ${REPO_URL} /tmp/app.tar.gz

RUN tar -xzf /tmp/app.tar.gz --strip-components=1 -C /opt/StaticJinjaPlus && \
	rm -rf /tmp/app.tar.gz

RUN mv /opt/StaticJinjaPlus/templates_example /opt/StaticJinjaPlus/templates

RUN pip3 install --no-cache-dir -r requirements.txt

ENTRYPOINT ["python3", "main.py"]

CMD ["--help"]

